### ISSUE TITLE
Cors policy changes

### ISSUE THREAD

**Issue by tstdenis** [cotestatnt/Arduino-Google-API#1]
Per this [issue](https://github.com/gridaco/cors.sh/issues/7), the CORS policy changed for Google. I have received an API-key and updated the TOKEN.vue file where the requests seems to originate per the code below:

`getGoogleTokens() {
      let payload = {
      	'code': this.authorization_code,
        'client_id': this.client_id,
        'client_secret': this.client_secret,
        'redirect_uri': this.redirect_uri,
        'grant_type': 'authorization_code'
      };

      const headers = {
      	'Access-Control-Allow-Origin': '*',
        'Access-Control-Max-Age': '600',
        'Access-Control-Allow-Methods': 'PUT,POST,GET,OPTIONS',
        'Access-Control-Allow-Headers': '*',
        'x-cors-grida-api-key': '----key inserted here----'
      };

      const proxyurl = "https://cors.bridged.cc/";
      axios
        .post(proxyurl + 'https://oauth2.googleapis.com/token', payload, { headers } )
        .then(response => {
          let json = {
            'redirect_uri': this.redirect_uri,
            'scope': this.scope,
            'api_key': this.api_key,
            'client_id': this.client_id,
            'client_secret': this.client_secret,
            'refresh_token': response.data.refresh_token,
            'access_token': response.data.access_token,
          };
          let obj = JSON.stringify(json, null, 2).replace(/\n/g, '   \n');
          this.jsonToSave = obj;
          this.gotTokens = true;
          this.waitTokens = false;
      });
    },`

When recompiled, it doesn't seem like the updates take as you can see from the Chrome output:
`:authority: cors.bridged.cc
:method: POST
:path: /https://oauth2.googleapis.com/token
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-CA,en-GB;q=0.9,en-US;q=0.8,en;q=0.7
access-control-allow-headers: *
access-control-allow-methods: PUT,POST,GET,OPTIONS
access-control-allow-origin: *
access-control-max-age: 600
content-length: 316
content-type: application/json;charset=UTF-8
origin: http://192.168.0.27
referer: http://192.168.0.27/
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="99", "Google Chrome";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36`

Notice how the new header does not appear. Could this be a compiling issue - meaning it is not picking up the changes made to Token.vue when it assembles all the files? Is there elsewhere in the code base that needs to change?

**Comment by cotestatnt** [comment]
Hi @tstdenis,
I'm sorry for really late reply. I didn't notice that someone had opened an issue in this repo :(

Actually I'm testing new version much much more stable and easy to use, where I have solved also the CORS policy issue.
I will upload soon the new sources, saty tuned!

It will add some dependecies, like ArduinoJson and one of my other library [ esp-fs-webserver](https://github.com/cotestatnt/esp-fs-webserver), which replace the webserver included now and adds some additional functionality (custom HTML in setup page and hidden fields like logo or webpage title).
