### ISSUE TITLE
Can't find PHP script

### ISSUE THREAD

**Issue by metinc** [cotestatnt/Arduino-Google-API#6]
The readme says there is a PHP script provided but where is it? I can't find it.

https://github.com/cotestatnt/Arduino-Google-API/blob/e4b39d9e62b442a807a9eebcb765f47851c1a5a2/README.md?plain=1#L29

And thank you for sharing this project.

**Comment by cotestatnt** [comment]
Hi @metinc , I probably forgot to upload files from beginning.
I just added the missing files.

Thanks you!
