### ISSUE TITLE
Authorization without hosting your own server

### ISSUE THREAD

**Issue by metinc** [cotestatnt/Arduino-Google-API#9]
I'm trying to find a solution to simplify the authorization with Google and I think I found something interesting when using the option "Desktop app". 

![image](https://github.com/cotestatnt/Arduino-Google-API/assets/1820121/daf9c96d-2000-4963-9553-5fd041160c35)

When using Google auth in desktop apps you pass a so called loopback IP to the Google server. For desktop apps this usually is localhost and any port. But we could use this loopback IP to pass the IP of our ESP device. 

From the Google Docs:

> The[ loopback IP address flow](https://developers.google.com/identity/protocols/oauth2/native-app#redirect-uri_loopback) supports the use of a loopback IP address or localhost as the host component of the redirect URI where credentials are sent to after a user approves an OAuth consent request.

Usage of the loopback IP address is described here:

https://developers.google.com/identity/protocols/oauth2/native-app#step-2:-send-a-request-to-googles-oauth-2.0-server

I know that there is a deprecated warning but that is only for mobile apps. 

Any thoughts on this? I will take another look at this after the holidays.

**Comment by cotestatnt** [comment]
This is really interesting! It could make project initial setup a lot easier.
I'll definitely look into it as soon as I can and start doing some tests too.

If you have news and would like to share it, that would be great.

**Comment by metinc** [comment]
I think this won't work. When I pass the local IP address of the ESP as loopback address I get an error: `The requested address is not valid in this context`

I guess only localhost or 127.0.0.1 are valid loopback addresses.
